### ISSUE TITLE
What happens in score_NN after calculating the distance of each query image from the template embeddings?

### ISSUE THREAD

**Issue by pratikm141** [mibastro/VPE#3]
Hi,
Can you please explain what happens in score_NN after finding the distance for each query from the template image embeddings.

and what does the IOU accuracy represent?. Is it simply the accuracy of classification for the query set?

**Comment by mibastro** [comment]
Hi, I misnamed variable. it is just classification accuracy, nothing to do with IOU.
In score_NN, the distances between the query and prototypes are calculated. And then the query is assigned to the class that has the closest distance.

**Comment by pratikm141** [comment]
Ok Thanks for the explanation.

For gtsrb2TT100K main_train_val_test.py fails because gtsrb2TT100K loader doesnot have "val" split specified. How should this be handled?

**Comment by pratikm141** [comment]
Ignore the above question, I just read your previous reply. 
gtsrb2TT100K does not have a validation set,
Thanks anyways.
